
GET http://localhost:3000

####

GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

####

POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route teste 1",
  "source_id": "1",
  "destination_id": "2"
} 

### Coisas do mapa

### Pegar o place id
GET http://localhost:3000/places?text=rua felipe de moura, são paulo, 110

### Pegar direções entre dois pontos
GET http://localhost:3000/directions?originId=EklSLiBEb20gVmlsYXJlcywgMTIwIC0gVmlsYSBkYXMgTWVyY2VzLCBTw6NvIFBhdWxvIC0gU1AsIDA0MTYwLTAwMCwgQnJhc2lsIjASLgoUChIJGwI4Yg5bzpQRys1adPvsJIwQeCoUChIJc9-A83JbzpQRSBkqnChDtHk&destinationId=ChIJWS8RYw5bzpQRk4dJM-LK96Q